-- Jalankan script ini setelah membuat dan memilih database qc.
-- Untuk membuat database, jalankan CREATE DATABASE qc; dari koneksi PostgreSQL lain.

CREATE TABLE IF NOT EXISTS public.mold_mapping
(
    mold_number VARCHAR(50) PRIMARY KEY,
    tipe_grid VARCHAR(50) NOT NULL
);

DO $$
DECLARE
    line_no INTEGER;
    table_name TEXT;
BEGIN
    FOR line_no IN 1..22 LOOP
        table_name := 'tbl_c' || lpad(line_no::TEXT, 2, '0');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS public.%I (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "timestamp" TIMESTAMP NOT NULL,
                tipe VARCHAR(50) NOT NULL,
                no_mold VARCHAR(50) NOT NULL,
                sisi_a DOUBLE PRECISION,
                sisi_b DOUBLE PRECISION,
                sisi_c DOUBLE PRECISION,
                sisi_d DOUBLE PRECISION,
                sisi_e DOUBLE PRECISION,
                sisi_f DOUBLE PRECISION,
                sisi_g DOUBLE PRECISION,
                sisi_h DOUBLE PRECISION,
                "avg" DOUBLE PRECISION
            )',
            table_name
        );
    END LOOP;
END
$$;
